name: Cassandra JMH
on:
  push:
    branches:
      - trunk

jobs:
  benchmark:
    name: jmh:tries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install tools
        run: |
          sudo apt install ant
      - name: Run benchmark
        run: |
          # This is where actions/setup-java puts it
          export JAVA_HOME=/opt/hostedtoolcache/Java_Adopt_jdk/11.0.27-6/x64
          ant microbench -Dbenchmark.name=tries

      - name: Analyze benchmark results with Nyrkiö
        uses: nyrkio/change-detection@v2
        with:
          tool: 'jmh'
          output-file-path: work/cassandra/cassandra/build/test/jmh-result.json

          # Pick up your token at https://nyrkio.com/docs/getting-started
          # Then head to https://github.com/USER_OR_ORG/PROJECT/settings/secrets/actions
          # Store the token you just created as a Repository secret. We'll use the variable name `secrets.NYRKIO_JWT_TOKEN` for it below.
          nyrkio-token: ${{ secrets.NYRKIO_JWT_TOKEN }}
